### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ghost** [rootm0s/Protectors#1]
Hello，I'm sorry that my English is terrible and I can't express myself enough. If my words are not polite, I beg your forgiveness。

I'm a Chinese student, who want to became a reverse engineer. When I learn how to unpack, I can't do this because I don't know its nature. So that I want to get something from your source code.  Would you mind give me some help about this . It is my gmail: 1214wjllz@gmail.com.

Thank you very much.

I'm sorry....I can't express myself enough.....

**Comment by ghost** [comment]
I don't know how to read your  code , the first step ....

**Comment by rootm0s** [comment]
I dont really teach out anything, all these "collections" of projects are for understanding different techniques used. 

If you really want to learn I suggest study the langauge you want to reverse engineer. It's nothing you learn over a night so keep that in mind!
